test 2

diff --git a/.github/workflows/firebase-hosting-merge.yml b/.github/workflows/firebase-hosting-merge.yml
--- a/.github/workflows/firebase-hosting-merge.yml
+++ b/.github/workflows/firebase-hosting-merge.yml
@@ -31,6 +31,15 @@ jobs:
       - name: Build application
         run: pnpm build
 
+      - name: Verify Firebase Secret Exists
+        run: |
+          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEAK_ALLOY_426016_B4 }}" ]; then
+            echo "Secret is missing"
+            exit 1
+          else
+            echo "Secret exists"
+          fi
+
       - name: Deploy to Firebase Hosting
         uses: FirebaseExtended/action-hosting-deploy@v0.10.0
 
